### ISSUE TITLE
Craftbukkit 1.8

### ISSUE THREAD

**Issue by ryanwarsaw** [AltitudeMapdev/Issues#102]
Yesterday morning Spigot released a updated build for 1.8, along with a updated build of Craftbukkit. they have implemented a new BuildTools system of distributing the code, thus drowning worries about the license. 

They have created a new Stash page as shown here: https://hub.spigotmc.org/stash/projects

One of those repositories is for Overcast's SportBukkit which will now continue thanks to the updated CraftBukkit and Spigot builds. ;-D

Hopefully this means that the Altitude project can continue!!!

**Comment by CoWinkKeyDinkInc** [comment]
I don't think Sponge would be a good idea at this point.

**Comment by CoWinkKeyDinkInc** [comment]
Pretty much the only reason it's good is because there is no "Copyright Stuff" involved, although many couldn't care less about some guy that isn't willing to sue the md_5 for apparently using his code.  Like why is this guy mad that his stuff is out there for anyone to use, and the point is that anyone can use it?
