### ISSUE TITLE
Owner field sometimes displays "Loading"

### ISSUE THREAD

**Issue by gcflames5** [AltitudeMapdev/Issues#99]
![Great job molen](https://i.imgur.com/bKItV5q.png)

**Comment by AustinLMayes** [comment]
MOMMY IM IN THE PICTURE!

**Comment by molenzwiebel** [comment]
Intentional behavior. Happens when the name of the owner is looked up, `Loading...` is shown while the request is going. If the request fails, `Loading...` stays until the scoreboard is refreshed (flag toggle, lock). Might change to not show any owner if it is not loaded, although that will make a name suddenly appear is the Mojang API is slow.

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Cache UUID and names?

**Comment by molenzwiebel** [comment]
I do, current setting is 10 minutes and UUID -> Name first checks the players that are online.
Note that it probably wasn't the limit the Mojang API has, as that is 600 requests every 5 minutes (and I can't imagine us doing 600 requests when we cache).

**Comment by AustinLMayes** [comment]
Maybe if it fails show something besides `Loading...` ?

**Comment by gcflames5** [comment]
Well I don't believe the cache actually works because I logged into the world for the first time, I saw my name, however, every time after that it said "Loading..." regardless of the flags I changed or if i rejoined the world
